### ISSUE TITLE
Alexa issue

### ISSUE THREAD

**Issue by wchulze** [arendst/Tasmota#10430]
PROBLEM DESCRIPTION

I have been using the Tasmota version 6.3.0 for about 20 Sonoff Basic's for several years and have not had any worries with the Belkin Wemo emulation. I control the sockets with Amazon Echo. Now I've added two Tuya dimmers to my IoT park. The setup - including the heartbeat - went without a hitch. With the Tasmota version 6.3.0, however, the HUE emulation does not work properly in conjunction with Alexa, ok. So I installed the current version (9.2.0) of Tasmata. The Tuya dimmers work fine. To my astonishment, there are now problems with network transmission. Alexa often reports "the device does not respond ...". In order to rule out that the problem comes from the dimmers, I installed version 9.2 on a Sonof Basic - with the result that the same problem now occurs there.

If the Sonoff website is called up in the browser (Chrome), there are sometimes waiting times of 6 seconds until the interface appears, which is very long. The "Sleep" setting is set to 40ms. Other values for Sleep do not change the behavior.

Tasmota shows an RSSI value of 54% at -68 dBm in the "information page", which is sufficient. MQTT is deactivated.

I have now experimented with different Tasmota versions: if the HUE emulation works in the version, there are problems with the WLAN access. That may be a coincidence. However, if an error occurs, the Belkin Wemo emulation has the same problem. For programming I use "Tasmota-PyFlasher-1.0" and delete the flash memory completely.

I have now varied the distance between the Sonoff and my router. From an RSSI of < 55% problems occur in version 9.2. Version 6.3 plays up to RSSI 25% without problems. The distance between the router and the Sonoff can be considerably greater with version 6.3.0, more than twice.

What can I do to solve the problem? I'm compiling the project with Visual Studio Code V1.50.1. Unfortunately, I have no more ideas at the moment. Thanks for a hint.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [y] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [y] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ y]Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [y] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [y] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [y] Device used (e.g., Sonoff Basic): Sonoff Basic
- [y] Tasmota binary firmware version number used:  9.2.0
  - [ ] Pre-compiled
  - [y] Self-compiled by Visual Studio Code
- [y] Flashing tools used: Tasmota-PyFlasher-1.0
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here: 
na

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
19:08:45 RSL: STATUS = {"Status":{"Module":1,"DeviceName":"Sonoff1","FriendlyName":["sonoff1","sonoff1t1"],"Topic":"tasmota","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":0,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
19:08:45 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T21:02:16","StartupUTC":"2021-01-05T21:06:29","Sleep":40,"CfgHolder":4617,"BootCount":44,"BCResetTime":"2021-01-02T19:14:44","SaveCount":98,"SaveAddress":"FA000"}}
19:08:45 RSL: STATUS2 = {"StatusFWR":{"Version":"9.2.0(tasmota)","BuildDateTime":"2021.01.02 15:53:45","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"392/699"}}
19:08:45 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["wolfgangtespe",""],"TelePeriod":300,"Resolution":"55C180C0","SetOption":["00008000","2805C8000100060000005A00000000000000","00000000","00006000","00000000"]}}
19:08:45 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":587,"Free":416,"Heap":26,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"14405E","FlashFrequency":40,"FlashMode":3,"Features":["00000407","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"}}
19:08:45 RSL: STATUS5 = {"StatusNET":{"Hostname":"tasmota-5664","IPAddress":"192.168.178.21","Gateway":"192.168.178.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.178.1","Mac":"5C:CF:7F:72:36:20","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
19:08:45 RSL: STATUS7 = {"StatusTIM":{"UTC":"2021-01-06T18:08:45","Local":"2021-01-06T19:08:45","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":99,"Sunrise":"08:42","Sunset":"17:09"}}
19:08:45 RSL: STATUS10 = {"StatusSNS":{"Time":"2021-01-06T19:08:45"}}
19:08:45 RSL: STATUS11 = {"StatusSTS":{"Time":"2021-01-06T19:08:45","Uptime":"0T21:02:16","UptimeSec":75736,"Heap":26,"SleepMode":"Dynamic","Sleep":40,"LoadAvg":24,"MqttCount":0,"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"xxxx","BSSId":"9C:C7:A6:30:yy:zz","Channel":1,"RSSI":50,"Signal":-75,"LinkCount":1,"Downtime":"0T00:00:03"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
na, 


### TO REPRODUCE
_Steps to reproduce the behavior:_

Update from Tasmota Version 6.3.0 to Tasmota Version 9.2.0


### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

See problem description above


### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

na

### ADDITIONAL CONTEXT
_Add any other context about the problem here._


**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Please, could you be so kind on completing the [troubleshooting template](https://github.com/arendst/Tasmota/issues/new/choose) in order to have more information so as to properly help you?

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by wchulze** [comment]
Sorry, I forget to fill the template. Hopefully you have enough information now.
Regards Wolfgang

**Comment by ascillato** [comment]
Please, set weblog to 4 and then copy the output of the console when you see this issue.

**Comment by Jason2866** [comment]
Since you upgraded from Tasmota 6.x using a older Arduino ESP8266 core it is always a good idea to initiate wifi recalibration. This is done by `reset 3` NO settings are lost. After device is back online it is neccessary to switch off / on the power supply. Only with off / on the new calibration settings are used.

**Comment by wchulze** [comment]
Hallo Jason2866
The upgrade is done by erase the  flash with Tasmota-PyFlasher-1.0. I think no calibration is necessary. I have setup the dive manually after "upgrade"
-----------
Adrian, this is the console output after failed connection from Alexa.

14:26:02 UDP: Packet (119)
14:26:15 WIF: Prüfe Verbindung...
14:26:35 WIF: Prüfe Verbindung...
14:26:55 WIF: Prüfe Verbindung...
14:27:15 WIF: Prüfe Verbindung...
14:27:35 WIF: Prüfe Verbindung...
14:27:55 WIF: Prüfe Verbindung...
14:27:57 UDP: Packet (119)
14:28:07 UDP: Packet (119)
14:28:15 WIF: Prüfe Verbindung...
14:28:23 UDP: Packet (119)
14:28:23 UDP: Packet (119)
14:28:24 UPP: Hue 3 Antwortpakete gesendet zu 192.168.178.57:50000
14:28:24 HTP: Hue-Setup
14:28:25 HTP: Hue-API (/723620/lights) from 192.168.178.57
14:28:25 HTP: Hue Result ({"119759361":{"state":{"on":false,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"sonoff1","modelid":"Generic","manufacturername":"Tasmota","uniqueid":"5c:cf:7f:72:36:20:00:11-1"},"119759362":{"state":{"on":false,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"sonoff1t1","modelid":"Generic","manufacturername":"Tasmota","uniqueid":"5c:cf:7f:72:36:20:00:11-2"}})
14:28:25 HTP: Hue-API (/723620/lights/119759361) from 192.168.178.57
14:28:25 /lights path=/lights/119759361
14:28:25 HTP: Hue Result ({"state":{"on":false,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"sonoff1","modelid":"Generic","manufacturername":"Tasmota","uniqueid":"5c:cf:7f:72:36:20:00:11-1"})
14:28:25 HTP: Hue-API (/723620/lights/119759362) from 192.168.178.57
14:28:25 /lights path=/lights/119759362
14:28:25 HTP: Hue Result ({"state":{"on":false,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"sonoff1t1","modelid":"Generic","manufacturername":"Tasmota","uniqueid":"5c:cf:7f:72:36:20:00:11-2"})
14:28:25 HTP: Hue-API (/723620/lights) from 192.168.178.57
14:28:25 HTP: Hue Result ({"119759361":{"state":{"on":false,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"sonoff1","modelid":"Generic","manufacturername":"Tasmota","uniqueid":"5c:cf:7f:72:36:20:00:11-1"},"119759362":{"state":{"on":false,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"sonoff1t1","modelid":"Generic","manufacturername":"Tasmota","uniqueid":"5c:cf:7f:72:36:20:00:11-2"}})
14:28:29 UDP: Packet (119)
14:28:30 HTP: Konsole
14:28:35 WIF: Prüfe Verbindung...
14:28:55 WIF: Prüfe Verbindung...
-------------
"State info"
14:47:20 HTP: Konsole
14:47:25 CMD: state
14:47:25 SRC: WebConsole from 192.168.178.85
14:47:25 CMD: Gruppe 0, Index 1, Befehl "STATE", Daten ""
14:47:25 RSL: RESULT = {"Time":"2021-01-07T14:47:25","Uptime":"0T16:06:35","UptimeSec":57995,"Heap":26,"SleepMode":"Dynamic","Sleep":40,"LoadAvg":24,"MqttCount":0,"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"wolfgangtespe","BSSId":"9C:C7:A6:30:9E:65","Channel":1,"RSSI":40,"Signal":-80,"LinkCount":1,"Downtime":"0T00:00:04"}}
14:47:35 WIF: Prüfe Verbindung...
14:47:55 WIF: Prüfe Verbindung...
14:48:02 UDP: Packet (119)
14:48:07 UDP: Packet (119)
14:48:15 WIF: Prüfe Verbindung...

Wolfgang

**Comment by Jason2866** [comment]
Take care that NO Alexa app or program is running. If this is the case the packets are send to the wrong address.
See example (first Alexa app, second real Echo device!):
```
15:44:11.750 UPP: Hue 3 response packets sent to 192.168.2.162:50000
15:44:11.961 HTP: Hue setup
15:45:57.348 UPP: Hue 3 response packets sent to 192.168.2.140:50000
15:45:57.799 HTP: Hue setup
```

**Comment by wchulze** [comment]
Hello Jason2866
Yesterday I have set up the sonoff and in addition, I deleted it in Alexa in the Internet browser and reconnected it. Otherwise the HUE emulation could not work.

Normally, 99, ..% , everything works fine. The problem occurs only sporadically, especially with low signal levels on the Sonnoff. That with not running an Alexa app would mean that all smartphones must have to be switched off, wow.

Why should Amazon send a nonsensical command to one of my echoes when the level at the Sonnoff is low?

Here is a working recording just some minutes ago:

16:26:06 WIF: Prüfe Verbindung...
16:26:12 HTP: Hue-API (/723620/lights/119759361/state) from 192.168.178.57
16:26:12 HTP: Hue POST-Argumente ({"on":true})
16:26:12 SRC: Hue
16:26:12 RSL: RESULT = {"POWER1":"ON"}
16:26:12 RSL: POWER1 = ON
16:26:12 HTP: Hue Result ([{"success":{"/lights/119759361/state/on":true}}])
16:26:12 HTP: Hue-API (/723620/lights/119759361) from 192.168.178.57
16:26:12 /lights path=/lights/119759361
16:26:12 HTP: Hue Result ({"state":{"on":true,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"sonoff1","modelid":"Generic","manufacturername":"Tasmota","uniqueid":"5c:cf:7f:72:36:20:00:11-1"})
16:26:26 WIF: Prüfe Verbindung...

Wolfgang

**Comment by wchulze** [comment]
I've just looked at the console output of the Sonoff.
All the output there come from the Sonoff itself and not an Echo.

The Sonoff has been addressed by my echo. I find the reaction in the console.

Why does the Sonoff send to 192.168.178.57 the echo in my kitchen near the router
14:28:24 UPP: Hue 3 Antwortpakete gesendet zu 192.168.178.57:50000

carries out a setup
4:28:24 HTP: Hue-Setup

and gets from the echo
14:28:25 HTP: Hue-API (/723620/lights) from 192.168.178.57

and then send
14:28:25 HTP: Hue Result ({"119759361":{"state":{"on":false,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"sonoff1","modelid":"Generic","manufacturername":"Tasmota","uniqueid":"5c:cf:7f:72:36:20:00:11-1"},"119759362":{"state":{"on":false,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"sonoff1t1","modelid":"Generic","manufacturername":"Tasmota","uniqueid":"5c:cf:7f:72:36:20:00:11-2"}})

I don't see any communication between the Alexa app and the Echo, as well.

If it goes well it looks like this:
22:58:01 HTP: Hue-API (/723620/lights/119759361/state) from 192.168.178.57
22:58:01 HTP: Hue POST-Argumente ({"on":true})
22:58:01 SRC: Hue
22:58:01 RSL: RESULT = {"POWER1":"ON"}
22:58:01 RSL: POWER1 = ON
22:58:01 HTP: Hue Result ([{"success":{"/lights/119759361/state/on":true}}])
22:58:01 HTP: Hue-API (/723620/lights/119759361) from 192.168.178.57
22:58:01 /lights path=/lights/119759361
22:58:01 HTP: Hue Result ({"state":{"on":true,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"sonoff1","modelid":"Generic","manufacturername":"Tasmota","uniqueid":"5c:cf:7f:72:36:20:00:11-1"})

1. Somehow there seems to be something wrong with the communication between Tasmota and the Echo.

2: There are no problems of this kind with Tasmota version 6.3.0.

3: I have not yet dig into the Belkin Wemo emulation with V9.2.0 except that if it comes to an error. Alexa acknowledges with "The device does not answer ...".

Wolfgang

**Comment by Jason2866** [comment]
I can not reproduce the issue you have. Device with low rssi do work for me too (Webfrontend, Alexa  and mqtt).

**Comment by wchulze** [comment]
As with the HUE emulation, the error only occurs rarely and sporadically. I think that the wrong behavior is probably not an emulation problem but rather to find in the communication between Tasmota and an Amazon echo.

I have now deactivated all Alexa apps on my smartphones and tablets for testing purposes. Unfortunately the problem remains, no change.

On the test device (Sonoff Basic) I activated the Belkin WeMo emulation, then deleted it from Amazon and reactivated it. I will investigate the behavior.

Wolfgang

**Comment by wchulze** [comment]
That you cannot reproduce the issue may be due to the nature of the sporadic occurrence.
The error quickly appeared in my arrangement.

Here is the log from the console.

21:10:11 UDP: Packet (119)
21:10:11 UDP: Packet (119)
21:10:13 WMO: WeMo Type 2, Antwort gesendet to 192.168.178.57:50000
21:10:15 HTP: WeMo-Setup from 192.168.178.57
21:10:16 HTP: Konsole
21:10:17 HTP: WeMo basic event from 192.168.178.57
21:10:18 UDP: Packet (119)
21:10:25 WIF: Prüfe Verbindung...
21:10:38 UDP: Packet (119)
21:10:38 UDP: Packet (119)
21:10:39 UDP: Packet (119)
21:10:45 WIF: Prüfe Verbindung...

I added the "Status".

21:11:04 CMD: state
21:11:04 SRC: WebConsole from 192.168.178.85
21:11:04 CMD: Gruppe 0, Index 1, Befehl "STATE", Daten ""
21:11:04 RSL: RESULT = {"Time":"2021-01-07T21:11:04","Uptime":"0T01:22:23","UptimeSec":4943,"Heap":25,"SleepMode":"Dynamic","Sleep":40,"LoadAvg":24,"MqttCount":0,"POWER":"OFF","Wifi":{"AP":1,"SSId":"wolfgangtespe","BSSId":"9C:C7:A6:30:9E:65","Channel":1,"RSSI":40,"Signal":-80,"LinkCount":1,"Downtime":"0T00:00:04"}}
21:11:05 WIF: Prüfe Verbindung...

This console printout  shows a good transmission afterwards.

21:15:45 WIF: Prüfe Verbindung...
21:16:05 WIF: Prüfe Verbindung...
21:16:09 HTP: WeMo basic event from 192.168.178.57
21:16:09 SRC: Wemo
21:16:09 RSL: RESULT = {"POWER":"ON"}
21:16:09 RSL: POWER = ON
21:16:09 HTP: WeMo basic event from 192.168.178.57
21:16:13 HTP: Konsole

**Comment by Jason2866** [comment]
You can try ` setoption41 60`

**Comment by wchulze** [comment]
Thanks. Good idea with the ARP. Already had the assumption that my Fritzbox ... falls asleep. Unfortunately, the ARP doesn't help either.

19:15:14 UDP: Packet (119)
19:15:28 WIF: Sending Gratuitous ARP
19:15:30 WIF: Prüfe Verbindung...
19:15:38 UDP: Packet (119)
19:15:38 UDP: Packet (119)
19:15:38 UDP: Packet (119)
19:15:40 UPP: Hue 3 Antwortpakete gesendet zu 192.168.178.57:50000
19:15:40 HTP: Hue-Setup
19:15:40 HTP: Hue-API (/723620/lights) from 192.168.178.57
19:15:40 HTP: Hue Result ({"119759361":{"state":{"on":false,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"sonoff1","modelid":"Generic","manufacturername":"Tasmota","uniqueid":"5c:cf:7f:72:36:20:00:11-1"},"119759362":{"state":{"on":false,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"sonoff1t1","modelid":"Generic","manufacturername":"Tasmota","uniqueid":"5c:cf:7f:72:36:20:00:11-2"}})
19:15:40 HTP: Hue-API (/723620/lights/119759361) from 192.168.178.57
19:15:40 /lights path=/lights/119759361
19:15:40 HTP: Hue Result ({"state":{"on":false,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"sonoff1","modelid":"Generic","manufacturername":"Tasmota","uniqueid":"5c:cf:7f:72:36:20:00:11-1"})
19:15:40 HTP: Hue-API (/723620/lights/119759362) from 192.168.178.57
19:15:40 /lights path=/lights/119759362
19:15:40 HTP: Hue Result ({"state":{"on":false,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"sonoff1t1","modelid":"Generic","manufacturername":"Tasmota","uniqueid":"5c:cf:7f:72:36:20:00:11-2"})
19:15:41 HTP: Hue-API (/723620/lights) from 192.168.178.57
19:15:41 HTP: Hue Result ({"119759361":{"state":{"on":false,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"sonoff1","modelid":"Generic","manufacturername":"Tasmota","uniqueid":"5c:cf:7f:72:36:20:00:11-1"},"119759362":{"state":{"on":false,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"sonoff1t1","modelid":"Generic","manufacturername":"Tasmota","uniqueid":"5c:cf:7f:72:36:20:00:11-2"}})
19:15:42 UDP: Packet (119)
19:15:42 UDP: Packet (119)
19:15:42 UDP: Packet (119)

I rummaged through the source code. The message "Hue 3 Antwortpakete gesendet zu ..." seems to be issued when a UDP message has timed out. The time for this is calculated by:
    uint32_t response_delay = UDP_MSEARCH_SEND_DELAY + ((millis () & 0x7) * 100);
and is possibly quite tight with1500 ms.

Is it worth increasing this time?

Wolfgang

**Comment by wchulze** [comment]
Increasing the waiting time was unsuccessful. The behavior is basically the same as before, except that the error message from Alexa is announced later.

Wolfgang

**Comment by s-hadinger** [comment]
@wchulze I removed completely the time in #10514 although I don't think it's the issue here. Please try with the new version.

**Comment by wchulze** [comment]
Thanks. I don't think it will solve the problem. It is still worth a try. Where can I find the version?

Wolfgang

**Comment by ascillato2** [comment]
http://ota.tasmota.com/tasmota/tasmota.bin.gz

**Comment by wchulze** [comment]
Thanks. I installed version 9.2.0.3. The result is even worse. Dropouts now occur with an RSSI of 70% and a field strength of -64dBm.

In order to exclude the router (FritzBox) I tried yesterday with a Ciso, same problem.

15:07:30.878 UDP: Packet (119)
15:07:30.887 UPP: Hue 3 response packets sent to 192.168.178.29:50000
15:07:30.918 UDP: Packet (119)
15:07:30.920 UDP: Packet (119)
15:07:39.628 WIF: Checking connection...
15:07:42.600 HTP: Hue API (/723620/lights/119759361/state) from 192.168.178.57
15:07:42.602 HTP: Hue POST args ({"on":false})
15:07:42.609 SRC: Hue
15:07:42.613 RSL: RESULT = {"POWER1":"OFF"}
15:07:42.616 RSL: POWER1 = OFF
15:07:42.618 HTP: Hue Result ([{"success":{"/lights/119759361/state/on":false}}])
15:07:42.720 HTP: Hue API (/723620/lights/119759361) from 192.168.178.57
15:07:42.723 /lights path=/lights/119759361
15:07:42.732 HTP: Hue Result ({"state":{"on":false,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"son...
15:07:51.578 UDP: Packet (119)
15:07:54.392 HTP: Console
15:08:00.110 WIF: Checking connection...
15:08:13.791 CMD: state
15:08:13.794 SRC: WebConsole from 192.168.178.85
15:08:13.798 CMD: Group 0, Index 1, Command "STATE", Data ""
15:08:13.804 RSL: RESULT = {"Time":"2021-01-11T15:08:13","Uptime":"0T00:02:04","UptimeSec":124,"Heap":26,"SleepMode":"Dynamic","Sleep":40,"LoadAvg":24,"MqttCount":0,"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"wolfgangtespe","BSSId":"9C:C7:A6:30:9E:65","Channel":1,"RSSI":70,"Signal":-64,"LinkCount":1,"Downtime":"0T00:00:04"}}

Wolfgang

**Comment by ascillato** [comment]
In order to rule out a scrambled settings in the wifi parameters of the SDK, please do a `reset 3` to recalibrate the wifi radio settings and then do a `reset 6` to reset internal Tasmota settings to default. After that, please, re configure your device manually and test again. Thanks.

**Comment by wchulze** [comment]
Thanks, I had made a fresh instalation with Tasmota-PyFlasher-1.0. Then the state from 9.2.0.0 restored. Will do  command reset 3 and 6 and then make the setting by hand.

Wolfgang

**Comment by wchulze** [comment]
Here is the result after a few minutes. With low RSSI and moderate level. But it should work anyway.

16:45:03.219 UDP: Packet (119)
16:45:03.228 UPP: Hue 3 response packets sent to 192.168.178.57:50000
16:45:03.622 HTP: Hue setup
16:45:03.722 HTP: Hue API (/723620/lights) from 192.168.178.57
16:45:03.739 HTP: Hue Result ({"119759361":{"state":{"on":true,"alert":"none","effect":"none","reachable":true},"type":"Extended color light"...
16:45:03.823 HTP: Hue API (/723620/lights/119759361) from 192.168.178.57
16:45:03.826 /lights path=/lights/119759361
16:45:03.836 HTP: Hue Result ({"state":{"on":true,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"Sono...
16:45:03.923 HTP: Hue API (/723620/lights/119759362) from 192.168.178.57
16:45:03.927 /lights path=/lights/119759362
16:45:03.936 HTP: Hue Result ({"state":{"on":false,"alert":"none","effect":"none","reachable":true},"type":"Extended color light","name":"Son...
16:45:04.022 HTP: Hue API (/723620/lights) from 192.168.178.57
16:45:04.039 HTP: Hue Result ({"119759361":{"state":{"on":true,"alert":"none","effect":"none","reachable":true},"type":"Extended color light"...
16:45:05.973 UDP: Packet (119)
16:45:08.078 WIF: Checking connection...
16:45:18.049 UDP: Packet (119)
16:45:24.108 UDP: Packet (119)
16:45:28.676 UDP: Packet (119)
16:45:30.409 HTP: Console
16:45:42.741 UDP: Packet (119)
16:45:43.637 UDP: Packet (119)
16:45:43.639 UDP: Packet (119)
16:45:43.642 UDP: Packet (119)
16:45:44.193 CMD: state
16:45:44.195 SRC: WebConsole from 192.168.178.85
16:45:44.199 CMD: Group 0, Index 1, Command "STATE", Data ""
16:45:44.204 RSL: RESULT = {"Time":"2021-01-11T16:45:44","Uptime":"0T00:18:17","UptimeSec":1097,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER1":"ON","POWER2":"OFF","Wifi":{"AP":1,"SSId":"wolfgangtespe","BSSId":"9C:C7:A6:30:9E:65","Channel":1,"RSSI":38,"Signal":-81,"LinkCount":1,"Downtime":"0T00:00:03"}}

Wolfgang

**Comment by ascillato** [comment]
`"RSSI":38` is very low. With that poor wifi coverage, you should expect low response and/or commands to be missed.

The Wifi signal coverage can not be solved by software. You need to expand your wifi coverage with extra wifi routers.

**Comment by wchulze** [comment]
That is known. I chose the bad place just to get the problem faster. In the problem descrition on the top I wrote

_**I have now varied the distance between the Sonoff and my router. From an RSSI of < 55% problems occur in version 9.2. Version 6.3 plays up to RSSI 25% without problems. The distance between the router and the Sonoff can be considerably greater with version 6.3.0, more than twice.**_

Wolfgang

**Comment by s-hadinger** [comment]
Your logs show normal Hue discovery
I'm afraid the issue comes from something else

**Comment by wchulze** [comment]
To find out where the problem might come from, I installed a different firmware for test purposes.
Two screen shots of the result are  shown below.

![image](https://user-images.githubusercontent.com/41591541/104224846-cfc1e700-5445-11eb-8bd8-4daed08ac601.png)

#############################################################################################

![image](https://user-images.githubusercontent.com/41591541/104224489-59bd8000-5445-11eb-9781-1630999a08e1.png)


There are 2 Sonoff baisc. They are next to each other in the same place with different firmware.
Same SDK and core version. I am confused.

Wolfgang

**Comment by Jason2866** [comment]
Different hardware (not a single device is exactly the same) different places (yes a few cm does care!). The values are similar. Nothing what surprises. Wlan is HF

**Comment by wchulze** [comment]
Rss 34% is similar to 78%, mhm.
I am very aware of he high frequency properties (I developed HF modules @Philips).
If there are only slight reflectionsin a distance of Lamda , a few cm does not matter. That is the case.

In addition,  tried that with the same hardware. the result can be compared. A few dB of filed strenght  (3..4, mybe 6 ) difference is normal. The signal changes in this order of magnitude.
That doesn't explain the behavior. 

Here, just for the sake of completeness:

**_Tasmota version 6.3.0
Build Date & Time 03/02/2019 11:16:17 AM
Core / SDK version 2_3_0 / 1.5.3 (aec24ac9)_**

without any dropouts over the livespan with a poor RSSI.


20:39:54 CMD: weblog 4
20:39:54 RSL: RESULT = {"WebLog":4}
20:39:54 CFG: in Flash gespeichert am FB, zählen 1723, Bytes 3584
20:39:59 HTP: WeMo basic event
20:39:59 SRC: Wemo
20:39:59 RSL: RESULT = {"POWER":"OFF"}
20:39:59 RSL: POWER = OFF
20:39:59 HTP: WeMo basic event
20:40:00 WIF: Prüfe Verbindung...
20:40:00 WIF: verbunden
20:40:11 HTP: WeMo basic event
20:40:11 SRC: Wemo
20:40:11 RSL: RESULT = {"POWER":"OFF"}
20:40:11 RSL: POWER = OFF
20:40:11 HTP: WeMo basic event
20:40:18 CMD: state
20:40:18 SRC: WebConsole from 192.168.178.85
20:40:18 RSL: empfangenes topic /state, Datengröße 0, Daten 
20:40:18 RSL: Gruppe 0, Index 1, Befehl STATE, Daten 
20:40:18 RSL: RESULT = {"Time":"2021-01-11T20:40:18","Uptime":"2T05:19:29","Vcc":3.226,"POWER":"OFF","Wifi":{"AP":1,"SSId":"wolfgangtespe","BSSId":"9C:C7:A6:30:9E:65","Channel":1,"RSSI":28}}
20:40:20 WIF: Prüfe Verbindung...

Wolfgang

**Comment by ascillato** [comment]
Arduino core version 2.3.0 is known to report a higher RSSI but it is wrong. The more approximate value to the reality is from the latest core.

Also, core 2.3.0 is very old and has serious security bugs. You should stop using it right now (If anyone goes close to your home and broadcast a wifi network with their phone, using the same SSID as yours but without password, any software based on core 2.3.0 will connect to it and will provide full access to your device - OTA updates etc.)

Also core 2.3.0 is deprecated and no longer supported anymore. It uses a lot of energy compared to latest core and have other stability issues.

With a RSSI below 50%, the wifi connection is not super reliable. You need 60% or more for a good connection.

**Comment by ascillato** [comment]
I have done a huge amount of tests with several brands of routers and several devices types of ESP8266, when we were testing which SDK version of the Arduino core was more stable.

That is why, a connection below 35% is not reliable at all. You need a better wifi coverage. Take into account to have at least 60% RSSI or add Access Points to increase your wifi coverage. If you can't, you can change to one of the wemos mini that have external antenna and will increase about 20% the measured RSSI.

**Comment by wchulze** [comment]
Thanks for the safety instructions. How does a new core protect against this behavior?

I believe that your test was very successful. How I could build a mesh is clear to me.

Normally  I don't run Tasmota under such difficult conditions. I explaid why I did it.
The levels are usually> -60 dBm (RSSI> 70% ). But, as I have already described above, sporadic dropouts occur with V9.0.0 at these levels. Quite seldom, but remarkable because in my living room, kitchen, ... the lighst sometimes does not go on / off. My wife looks funny then.

It could also be possible that the channel load plays a role. Switching to other channels didn't help.

My FriztBox can record the channel utilization.
Seems like worries occur at values over 20%. Difficult to reproduce.
That shouldn't play a role with the small amount of data transmitted by Tasmota, but who knows?


![image](https://user-images.githubusercontent.com/41591541/104241198-92695380-545d-11eb-9fb6-be11fee30f01.png)

**Comment by ascillato** [comment]
> How does a new core protect against this behavior?

The actual Arduino core don't have that bug. That simple attack doesn't work now. That is why, update to latest is highly recommended.

> It could also be possible that the channel load plays a role. Switching to other channels didn't help.

Obviously, you have to measure the channel utilization from your wifi and the interference from your neighbours, and choose the one that is free or less used.

> Quite seldom, but remarkable because in my living room, kitchen, ... the lighst sometimes does not go on / off. My wife looks funny then.

That is just with Alexa right? With MQTT you don't have that issue right? And you have access to the webinterface of your device when it didn't respond to Alexa? If not, your issue is the ARP Table of your Fritzbox.

**Comment by wchulze** [comment]
Thanks for the detailed answer.
I don't know exactly whether the problem is to be attributed to Alexa. With Alexa, I expect rather symtomatic and not sporadic errors.

I don't use MQTT. I use Alexa and HTTP commands via RCoid.

When I access Tasmota via the web interface, the problem is typically no longer available ( sporadic dropouts )

In order to identify an ARP table problem I tried 2 routers: FritzBox and Cisco.
Gratuitous ARP with setoption41 60 was also unsuccessful.

Wolfgang

**Comment by ascillato** [comment]
When your device is not reachable, please, do a ping to its known IP and try again. If after the ping, you can reach your device again, it is indeed a misconfiguration of your routers ARP table thay forgets the match IP/MAC Address.

**Comment by wchulze** [comment]
I know, thanks. The device is reachable.

Ping wird ausgeführt für 192.168.178.21 mit 32 Bytes Daten:
Antwort von 192.168.178.21: Bytes=32 Zeit=26ms TTL=255
Antwort von 192.168.178.21: Bytes=32 Zeit=41ms TTL=255
Antwort von 192.168.178.21: Bytes=32 Zeit=56ms TTL=255
Antwort von 192.168.178.21: Bytes=32 Zeit=64ms TTL=255

Ping-Statistik für 192.168.178.21:
    Pakete: Gesendet = 4, Empfangen = 4, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 26ms, Maximum = 64ms, Mittelwert = 46ms

**_When I access Tasmota via the web interface, the problem is typically no longer available ( sporadic dropouts )_**

**Comment by Jason2866** [comment]
Your Ping times are high. Normal values are <10 ms. Something is fishy in your Network

**Comment by ascillato** [comment]
Yes, ping times are much higher than normal. I also have ping times of <10ms for wifi devices (Tasmotas). My Network consists of 2 AP, 1 router and 82 devices where 73 are wifi and 64 are Tasmotized devices.  So, seems that you have an issue with your Router's configuration.

I can reproduce this issue only if I don't use Multicast-helper=full in my mikrotik router. Without this configuration I also have problems with other devices too. 

So, seems that your issue is not Tasmota related but more the configuration of your router and how that configuration interacts with the Arduino core. Yes, you didn't see this issue with the older Arduino core, but also the old wifi implementation of the wifi core wasn't complete and never uses the sleep function and DTIM. This made that some devices got overheated and start failing, besides the excess of energy used on them.

To solve your wifi issue, you need to change your wifi properties in your router as it have been long discussed in old issues.

**Comment by wchulze** [comment]
Since I didn't find anything in my router that could apply to problems. A consultation with AVM did not provide any new information. 

Therefore, for test purpose, I placed 2 Sonoffs near the router.

192.168.178.20 contains Tasomta and 192.168.178.80 ESPurna. Both firmware versions contain the same core. Information I have posted 2 days ago.

Then I pinged the Sonoffs several times. That should avoid start-up problems. Final result see below.

**_Tasmota_** 
C:\Windows\system32>ping 192.168.178.20

Ping wird ausgeführt für 192.168.178.20 mit 32 Bytes Daten:
Antwort von 192.168.178.20: Bytes=32 Zeit=62ms TTL=128
Antwort von 192.168.178.20: Bytes=32 Zeit=79ms TTL=128
Antwort von 192.168.178.20: Bytes=32 Zeit=99ms TTL=128
Antwort von 192.168.178.20: Bytes=32 Zeit=24ms TTL=128

Ping-Statistik für 192.168.178.20:
    Pakete: Gesendet = 4, Empfangen = 4, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 24ms, Maximum = 99ms, Mittelwert = 66ms

#################################################################

**_ESPurna_**
C:\Windows\system32>ping 192.168.178.80

Ping wird ausgeführt für 192.168.178.80 mit 32 Bytes Daten:
Antwort von 192.168.178.80: Bytes=32 Zeit=2ms TTL=255
Antwort von 192.168.178.80: Bytes=32 Zeit=2ms TTL=255
Antwort von 192.168.178.80: Bytes=32 Zeit=1ms TTL=255
Antwort von 192.168.178.80: Bytes=32 Zeit=2ms TTL=255

Ping-Statistik für 192.168.178.80:
    Pakete: Gesendet = 4, Empfangen = 4, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 1ms, Maximum = 2ms, Mittelwert = 1ms

mhm, Wolfgang

**Comment by arendst** [comment]
FWIW:
```
PS C:\WINDOWS\system32> ping pow3 -n 10

Pinging pow3 [192.168.2.194] with 32 bytes of data:
Reply from 192.168.2.194: bytes=32 time=295ms TTL=255
Reply from 192.168.2.194: bytes=32 time=175ms TTL=255
Reply from 192.168.2.194: bytes=32 time=86ms TTL=255
Reply from 192.168.2.194: bytes=32 time=309ms TTL=255
Reply from 192.168.2.194: bytes=32 time=2ms TTL=255
Reply from 192.168.2.194: bytes=32 time=2ms TTL=255
Reply from 192.168.2.194: bytes=32 time=2ms TTL=255
Reply from 192.168.2.194: bytes=32 time=1ms TTL=255
Reply from 192.168.2.194: bytes=32 time=2ms TTL=255
Reply from 192.168.2.194: bytes=32 time=2ms TTL=255

Ping statistics for 192.168.2.194:
    Packets: Sent = 10, Received = 10, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 1ms, Maximum = 309ms, Average = 87ms
```

**Comment by s-hadinger** [comment]
Interesting. I'm seeing the same behavior. 

First 3 or 4 packets are very slow then single digit ms. 

```
PING 192.168.2.201 (192.168.2.201): 56 data bytes
64 bytes from 192.168.2.201: icmp_seq=0 ttl=254 time=250.548 ms
64 bytes from 192.168.2.201: icmp_seq=1 ttl=254 time=168.080 ms
Request timeout for icmp_seq 2
64 bytes from 192.168.2.201: icmp_seq=3 ttl=254 time=4.866 ms
64 bytes from 192.168.2.201: icmp_seq=4 ttl=254 time=3.101 ms
64 bytes from 192.168.2.201: icmp_seq=5 ttl=254 time=2.551 ms
64 bytes from 192.168.2.201: icmp_seq=6 ttl=254 time=3.537 ms
64 bytes from 192.168.2.201: icmp_seq=7 ttl=254 time=3.844 ms
```

**Comment by ascillato** [comment]
> First 3 or 4 packets are very slow then single digit ms.

That is just because of the energy saving feature of sleep. If you have sleep 50, Tasmota uses very little energy and it is very responsive. If you use sleep 0, Tasmota will give you small ping time also in the firsts attempts, but it uses a lot more energy.

**Comment by arendst** [comment]
Agree with @ascillato. Tasmota lowest sleep mode is still WIFI_MODEM_SLEEP. Espurna's default sleep mode is WIFI_NONE_SLEEP (source: Espurna general.h)
```
#ifndef WIFI_SLEEP_MODE
#define WIFI_SLEEP_MODE             WIFI_NONE_SLEEP        // WIFI_NONE_SLEEP, WIFI_LIGHT_SLEEP or WIFI_MODEM_SLEEP
#endif
```

For a test I changed tasmota's WIFI_MODEM_SLEEP to WIFI_NONE_SLEEP too and receive this:
```
PS C:\WINDOWS\system32> ping wemos4 -n 10

Pinging wemos4 [192.168.2.226] with 32 bytes of data:
Reply from 192.168.2.226: bytes=32 time=2ms TTL=255
Reply from 192.168.2.226: bytes=32 time=2ms TTL=255
Reply from 192.168.2.226: bytes=32 time=2ms TTL=255
Reply from 192.168.2.226: bytes=32 time=12ms TTL=255
Reply from 192.168.2.226: bytes=32 time=4ms TTL=255
Reply from 192.168.2.226: bytes=32 time=2ms TTL=255
Reply from 192.168.2.226: bytes=32 time=2ms TTL=255
Reply from 192.168.2.226: bytes=32 time=2ms TTL=255
Reply from 192.168.2.226: bytes=32 time=2ms TTL=255
Reply from 192.168.2.226: bytes=32 time=3ms TTL=255

Ping statistics for 192.168.2.226:
    Packets: Sent = 10, Received = 10, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 2ms, Maximum = 12ms, Average = 3ms
```

So concluding, the initial Tasmota connection will be slow to enable wifi modem startup.

**Comment by arendst** [comment]
Try latest development with commands ``sleep 0`` and ``so60 0``. This will set the wifi modem sleep to NONE and should respond to your pings immediatly (like espurna does).

**Comment by s-hadinger** [comment]
I confirm setting `Sleep 0` removes the hickup.

Do you have any clue why with `Sleep 50` the wifi stabilizes to low latency after 2-5 seconds?

**Comment by wchulze** [comment]
I installed the version. 
After sleep 0 no more access possible, so60 was 0.
I had to flash the previous version 9.2.0.3 again -> Tasmota-PyFlasher-1.0 with clear.

Sleep 0 doesn't work there either, strange.

Wolfgang

**Comment by s-hadinger** [comment]
Device not responding with Sleep 0 is often a sign that the power supply is not strong enough.

**Comment by wchulze** [comment]
Which one, the Sonoff-Basic???

Wolfgang

**Comment by funnyfrish** [comment]
disable mqtt and try it again with alexa.

Wolfgang Schulze <notifications@github.com> schrieb am Mi., 13. Jan. 2021,
21:37:

**Comment by ascillato** [comment]
> Do you have any clue why with Sleep 50 the wifi stabilizes to low latency after 2-5 seconds?

Yes, that is because of the dynamic sleep. You can use dynamic (default) or static sleep. In the dynamic sleep, Tasmota can reduce the sleep time if the cpu usage got incremented, and after that, it can go to 50ms again.
So, if you start using Tasmota (pinging or performing any task) Tasmota can reduce its sleep time to increase performance, and after it returns to idle state, will go back to the set sleep time. (@andrethomas great idea)

**Comment by ascillato** [comment]
> Which one, the Sonoff-Basic???

Sonoff basics are known to have a very weak power supply. But if sleep 0 makes your device unusable, it has a big issue. How did you flash your device?

**Comment by ascillato** [comment]
@funnyfrish 
> disable mqtt and try it again with alexa.

From the data shared on the first comment, mqtt is already disabled.

**Comment by wchulze** [comment]
**_Sonoff basics are known to have a very weak power supply._**
Yes, it is obviously not designed for additional strong power consumers (look at the circuit diagram of the Sonoff-Basic).

**_I had to flash the previous version 9.2.0.3 again -> Tasmota-PyFlasher-1.0 with clear._**
I tried tasmotizer also, nothing different, why should it.
With earlier Tasmato versions, sleep 0 runs without problems.

**_Dynamic sleep_**  and **_static sleep_** are well known by me. I am therefore not surprised by the behavior when pinging. That was never my problem either. Adrian noticed pinging behavior is a matter of setting of my FritzBoxi -> is not the case.

My problem are sporadic errors. Could perhaps be due to the sleep behavior.

Wolfgang

**Comment by Jason2866** [comment]
If sleep 0  makes your device nearly unresponsible there is NO DOUBT that the power supply is the reason for problems with this device. Andrethomas and i did a lot of research for this. The output was the function Dynamic Sleep routine from andrethomas to lower the MCU load (=decreasing needed power). Doing this the power supply is not so much "stressed".
Anyway this cant do no wonders. If i where you i would replace this known to be bad device. A sonoff basic is cheap in every aspect.

**Comment by wchulze** [comment]
**_Typical ping times with dynamic sleep_**
We actually looked carefully at the ping, see above.

**_Since every new version of Tasmota adds new features, the needed power in working state is increasing._**
Do you therefore think that Tasmota is no longer suitable for the Sonnoff-Basic ? Only in the Lite version? What about lamps, plugs ...

**_Less features -> less power consuming_**
So far, I was of the opinion that functions that are not used are not executed and thus do not require any computing time (power).

Wolfgang

**Comment by wchulze** [comment]
Just for info:

I have now briefly measured the power consumption of the sonoff basic under various conditions - **start-up** and **idling**, **relay** **on / off** with the same hardware.

![image](https://user-images.githubusercontent.com/41591541/104592514-9fa95c80-566e-11eb-97b7-d7036353c49c.png)


The power supply can obviously deliver 1.2 W. Otherwise software could not start and run, but it does so without complaint. The ramp-up time for theTasmota is approximately 4 seconds.

All of the above measurements were done with the **relay off**.  So we had 100% headroom in case of power.

Wolfgang

**Comment by Jason2866** [comment]
The average needed power is not the problem! You have to measure the peak current with a oscilloscope. 
The generated short current spikes are making trouble. Every driver / function compiled included in code does need CPU power. Use a stripped down version like Tasmota-lite for a sonoff basic.

Flash for example this "fat" Tasnota build https://github.com/Jason2866/Tasmota-specials/raw/firmware/firmware/tasmota/other/tasmota-platinum.bin to a NodeMCU and you will notice a massive slowdown of the ESP8266.

**Comment by Jason2866** [comment]
If you encounter the same issues with a NodeMCU powered via a reliable USB power supply please post your findings.
With all the indicators you gave and our own experiences your issues are sonoff basic related.

**Comment by wchulze** [comment]
**_The average needed power is not the problem! You have to measure the peak current with an oscilloscope._**
Ok we have an output capacitor of 330 uF. The 3.3 V regulator needs about 1V. The MCU may run down to 2.8 V. With this we can afford a voltage drop of approx. 1.2 V on the capacitor. This results in a time of 1.8 ms at a peak of 200 mA.
The converter runs at about 70kHz. This gives us aprox. 120 cycles in 1.8 ms to regulate this. Did I make a mistake? Is the peak greater?

**_With all the indicators you gave and our own experiences your issues are sonoff basic related._**
Yes, NodeMCU is not in my view at the moment. I think that would not be appropriate to the scope of this discussion thread.
My questions are essentially due to the Sonnoff Basic and Tuya-like devices with which I control my lighting.

**Comment by ascillato** [comment]
> Is the peak greater?

This analysis has been already done in older issues with oscilloscopes. While the ESP8266 is transmitting it can use more than 500 mA peak.

Anyway, the Tasmota-lite.bin have been used in sonoff basics with power issues. There are some batches of sonoff basics that you can run Tasmota-sensors.bin without issues and some other batches of sonoff basics that you can't (search for sonoff basic R2 issues). The R3 version is known to be much better than it predecesors.

Your initial issue is that is not reliable the control of your sonoff basic with Alexa. That operation insumes several steps that can influence on that. For example, which is the DTIM value of your router? If it is greater than 1(for example 3), your router is telling your devices to wait 300ms for the wifi beacon to interact. That summed up to interferences, sleep of your device, and a weak power regulator, can make to miss some http or udp commands.

So, which solution could be for your case? If you are not changing the hardware, you can modify some parameters in your router. Also, you can compile your lite version with emulation support and you can set sleep to a lower value.

Every setup is different so, some adaptations are needed sometimes. Most users don't have issues with Alexa.

**Comment by s-hadinger** [comment]
Thanks to Adrian's help, my lag issue (ping above) was greatly reduced by changing DTIM from 3 to 1 on the AP. Now ping times are always under 100ms at start and single digit after a few seconds.

**Comment by wchulze** [comment]
Thanks for your efforts.

The statement that the problem is to be attributed to Alexa is not mine. I also mentioned worries about HTTP access in the browser.

As far as I know, the DTIM value of a FritzBox is not adjustable. The FritzBox is however the most widely used router in Germany. 

As far as I understand, the current version of Tasmota is no longer suitable for a Sonoff Basic's ... For this I would first have to program and compile a special version. Quite complex. Is the "S" still valid in Tasmota?

At the moment I only see the possibility of using older Tasmota versions despite the security aspect. Because these versions run without any WLAN problems.

Wolfgang

**Comment by meingraham** [comment]
Compiling is quite simple actually, even I can do it successfully. Gitpod is a game changer.

Also, tasmota-lite meets the needs of the majority of Sonoff Basic use cases.

**Comment by ascillato** [comment]
> As far as I understand, the current version of Tasmota is no longer suitable for a Sonoff Basic's

Have you tried tasmota-lite.bin as asked? Please test it BEFORE claiming that is not suitable anymore.

Then, if after testing Tasmota-lite.bin, you want also to have emulation on Tasmota lite, the Compiling process is just a couple of clicks.

**Comment by wchulze** [comment]
I actually want to compile my Tasmota version locally to know what I'm doing.

I performed reset 3 and 6. After the min version, I installed the lite version and set it up again. The HUE emulation is running. Is that right? Alexa is respondig as normal.  My previous understanding was that the emulation is not available. Where can I find a summary of properties to be able to judge what is missing? Source code?

Wolfgang

**Comment by ascillato** [comment]
Please, test Tasmota Lite and tell us if it works fine in your setup.

**Comment by raphamotta** [comment]
I have the same problem with the latest tasmota lite firmware in my sonoff mini (wemo or hue, wherever)

**Comment by wchulze** [comment]
These are the first impressions:

After a fresh installation with clear EEPROM, the AP does not work. Connection establishment via WiFi , WebGui does not appear under 192.168.4.1. 
I use a  pre-release version and OTA to get Tasmota-lite V9.2.0.3 running.

Sleep 0: Ok
```
C:\Windows\system32>ping 192.168.178.21 -n 5

Ping wird ausgeführt für 192.168.178.21 mit 32 Bytes Daten:
Antwort von 192.168.178.21: Bytes=32 Zeit=3ms TTL=255
Antwort von 192.168.178.21: Bytes=32 Zeit=2ms TTL=255
Antwort von 192.168.178.21: Bytes=32 Zeit=3ms TTL=255
Antwort von 192.168.178.21: Bytes=32 Zeit=3ms TTL=255
Antwort von 192.168.178.21: Bytes=32 Zeit=3ms TTL=255

Ping-Statistik für 192.168.178.21:
    Pakete: Gesendet = 10, Empfangen = 10, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 2ms, Maximum = 4ms, Mittelwert = 2ms
```
Wolfgang

**Comment by ascillato** [comment]
Ok, so your issue is solved?

**Comment by wchulze** [comment]
Unfortunately not. My problem still occurs sporadically.

```
23:20:36.441 UDP: Packet (119)
23:20:37.375 UDP: Packet (119)
23:20:37.377 UDP: HUE
23:20:37.386 UPP: Hue 3 response packets sent to 192.168.178.29:50000
23:20:37.390 UDP: Packet (119)
23:20:42.485 UDP: Packet (119)
23:20:42.487 UDP: HUE
23:20:43.275 HTP: Console
45.353 UDP: Packet (119)
23:20:45.452 UDP: Packet (119)
23:20:45.454 UDP: HUE
23:20:56.375 CMD: state
23:20:56.378 SRC: WebConsole from 192.168.178.85
23:20:56.381 CMD: Group 0, Index 1, Command "STATE", Data ""
23:20:56.389 RSL: RESULT = {"Time":"2021-01-15T23:20:56","Uptime":"0T08:11:16","UptimeSec":29476,"Vcc":3.452,"Heap":29,"SleepMode":"Normal","Sleep":0,"LoadAvg":999,"MqttCount":0,"POWER1":"ON","POWER2":"OFF","Wifi":{"AP":1,"SSId":"wolfgangtespe","BSSId":"9C:C7:A6:30:9E:65","Channel":1,"RSSI":40,"Signal":-80,"LinkCount":1,"Downtime":"0T00:00:04"}}
```

Wolfgang

**Comment by raphamotta** [comment]
So, i flashed my sonoff mini with latest lite firmware, I have the same problem and it happens sporadically too:

15:07:43.848 HTP: Console
15:07:53.251 WIF: Checking connection...
15:07:54.664 UDP: Packet (119)
15:07:54.666 UDP: Packet (119)
15:07:54.669 UDP: Packet (119)
15:07:54.672 UDP: Packet (119)
15:07:54.870 UDP: Packet (119)
15:07:54.874 UDP: Packet (119)
15:07:54.876 UDP: Packet (119)
15:07:54.879 UDP: Packet (119)
15:07:55.075 UDP: Packet (119)
15:07:55.078 UDP: Packet (119)
15:07:55.080 UDP: Packet (119)
15:07:55.082 UDP: Packet (119)
15:08:00.604 UDP: Packet (119)
15:08:00.608 WMO: WeMo Type 2, Response sent to 192.168.1.245:50000
15:08:00.612 UDP: Packet (119)
15:08:00.614 UDP: Packet (119)
15:08:00.617 UDP: Packet (119)
15:08:00.621 UDP: Packet (119)
15:08:00.638 HTP: WeMo setup from 192.168.1.245
15:08:00.721 HTP: WeMo basic event from 192.168.1.245
15:08:01.654 HTP: WeMo basic event from 192.168.1.245
15:08:12.688 UDP: Packet (119)
15:08:12.691 UDP: Packet (119)
15:08:12.694 UDP: Packet (119)
15:08:12.697 UDP: Packet (119)
15:08:12.699 UDP: Packet (119)
15:08:12.702 UDP: Packet (119)
15:08:12.892 UDP: Packet (119)
15:08:12.896 UDP: Packet (119)
15:08:12.899 UDP: Packet (119)
15:08:12.901 UDP: Packet (119)
15:08:12.905 UDP: Packet (119)
15:08:12.907 UDP: Packet (119)
15:08:12.910 UDP: Packet (119)
15:08:13.095 UDP: Packet (119)
15:08:13.098 UDP: Packet (119)
15:08:13.102 UDP: Packet (119)
15:08:13.104 UDP: Packet (119)
15:08:13.107 UDP: Packet (119)
15:08:13.110 UDP: Packet (119)
15:08:13.252 WIF: Checking connection...
15:08:13.302 UDP: Packet (119)
15:08:14.109 HTP: Main Menu
15:08:15.575 HTP: Console

**Comment by 2bontb** [comment]
I just upgraded all my tasmota devices from 9.1.0 to 9.2.0. And I am experience now that a number of my devices have similar problems as descibed abovge. Wifi just does not connect for a number. I downgraded one to 9.1.0 and it immediately worked again.
So problem must have been introduced with additions between 9.1.0 and 9.2.0

**Comment by s-hadinger** [comment]
@2bontb there are many different problems described above. Is your problem wifi related or Alexa related?

**Comment by 2bontb** [comment]
Wifi related. Some of my tasmota devices did very slowly connect to WiFi after WiFi reset (took about an hour).
Next to the fact I flashed a new Wemos with 9.2.0, and it did not want to connect at all. When I reloaded it to 9.1.0 it connected immediate. Both versions on the Wemos was a clean flash using tasmotizer. The first wifi connect did not happen on 9.2.0.

**Comment by s-hadinger** [comment]
You can try `Reset 3` to recalibrate wifi. I suggest you reach out on Discord for help. 

I don't know of any new wifi issue on 9.2 and have been using it for some time

**Comment by raphamotta** [comment]
I did some tests and enabled IGMP snooping on my router. It seems the problem is fixed, could you try to do it @wchulze?

**Comment by ascillato** [comment]
> I did some tests and enabled IGMP snooping on my router. It seems the problem is fixed...

Well, you are totally right. IGMP must be enabled. In the Tasmota version with KNX, it is explained that IGMP must be enabled in the router in order to let multicast work. As Alexa uses UDP, this multicast repeater option, should be ON too. Some routers came with a weak Multicast support and if the router is busy, it discard the Multicast and UDP messages.

It is very good that you have brought this. It will be the solution for several users.

**Comment by wchulze** [comment]
I checked the IGMP settings on the FritzBox -> were already activated. So don't solve my sporadic dropouts.

**Comment by ascillato** [comment]
@wchulze 

Do you have an option to upgrade your Fritzbox router's firmware? For example, in older versions of mikrotik firmware, there were a bug that made the wifi unstable with some security settings. Upgrading solves that problem.

**Comment by wchulze** [comment]
Thank's, AutoUpdate is activated. Asks before every update. The firmware is up to date.

**Comment by 2bontb** [comment]
One more remark from my side on the WiFi problem I saw:
Altough some systems take a while to connect to WiFi, my general feeling is that the Wifi is much more stable,
Before upgrading to 9.2.0 I saw regular that WiFI got reconnected.
After upgrading to 9.2.0, I do not see that anymore. So once connected the WiFi connection is more stable.

**Comment by ascillato2** [comment]
Another possible source of UDP drop out is wifi interference. UDP messages are sent just once and not acked, so there isn't retransmissions if the reception have failed. Let's check how is your wifi configuration and the wifi channel usage.

Can you try the phone app called wifi analyzer? Or another similar to that, so as to check how crowded is the wifi channel you are using, if you channel is in auto or fixed, and how much is the bandwidth of the channel (20MHz, 40MHz)?

If it is 40MHz and there are several overlapping wifi networks, it is expected this type of issues. If that is your case,  please, try to set the channel to 20MHz of bandwidth and also choose a fixed channel where ther amount of other networks are minimal.

**Comment by wchulze** [comment]
That's exactly what I'm investigating right now.

UDP protocol is without control and handshake. That has to be implemented in the application (Alexa, HUE ....) I don't know whether that is the case.

I reduced the channel bandwidth to 20 MHz a few weeks ago. 
Thanks to a corresponding app, I am well aware of my WiFi channel environment.
I work - to see influences closely - with a fixed WiFi channel.

The FritzBox can create a protocol of the channel utilization. I noticed that the problem arises from a channel load of more than 15% .. 20%. These are nearly independent of the level (if > -85 dBm). If, at level approx >-50 dBm, the input stage of the ESPxxxis is internally regulated down it works correctly. In this case, the other users have less influence (regulated down -> into noise). All external channels are > 20 dBm below my local signal.

The behavior described above depends on the "espressif" core. From version 2.x I can observe the strange behavior, unfortunately there is no real alternative..

Wolfgang

**Comment by ascillato** [comment]
Your channel is fixed at 3 right?

Always, the best option is to use only channels 1, 6, 11 or 14. The others channels produce interference with nearby networks (This interference by overlapping don't occur in 5GHz but the ESP8266 don't support 5GHz).

If you move to channel 6, you will have less interferences. The best option would be to use channel 14 (that is supported by the ESP8266 and Tasmota), but as far as I know is not allowed in Germany.

As yours is in channel 3, you are having interferences from 4 different networks, so your devices and your AP are communicating to all those others AP and other devices trying to not transmit at the same time. As not every device of all those devices can not see each other, all those AP see overlapped transmittions. When you have several AP, but on the same channel, they time-multiplex the air usage and you will have less speed but no lost packages. That is why it is recommended only to use channels 1, 6, 11 or 14 and not in auto but in a fixed channel.

**Comment by wchulze** [comment]
Yes I use channel 3 in the moment. 

Channel 14 is not allowed in Germany.

The screen capture only shows a snapshot. The participants change over the day - channel field strength, etc.

The picture shows the field strength and not the data transmission. However, that seems to be the problem because the apparently participants do not negotiate the rights with each other properly.

If no free channel can be found, it would be perfect to lie directly on an occupied channel. Then the “Distributed Coordination Function” (DCF) takes effect. The FritzBox can handle that. Although this lowers the data throughput, it does not interfere with the small amounts of data from Tasmota.

The other participants in my WLAN - PC's, smartphone, lawn mower ... - have sufficiently good properties.

Wolfgang

**Comment by ascillato** [comment]
Great, please, tell us if fixing the channel to 1, 6 or 11 improves your network. 

From old issues, another solution found by other users was to put their Fritzbox in bridge-mode and use another router as the core of their wifi network. With a good router, this option will give you more versatility on the configuration options. I know that this option is more expensive because you need an extra hardware, but I wanted to mention it because is another solution to your problem.

**Comment by wchulze** [comment]
A new router is not a problem for me. But I want to be (quite) sure that this will solve the problem. To do this, however, the cause of it should first be found.

Whatever the case, DCF doesn't always seem particularly helpful.
It may be that the field strength levels change dynamically so that negotiating between the participants is not always possible. Then it crashes.

Channel 1 has already been eliminated because the problem is clearly evident. Channels 4 and 5 are not useful because of the overlap. I will test the other channels step by step; "NurDerHSV" and "Esszimmer" are on automatic channel search. This makes testing more difficult.

Lets see what happens.

Wolfgang

**Comment by wchulze** [comment]
I measured again and came - for one device- to the following result:

![image](https://user-images.githubusercontent.com/41591541/105576984-fdc4f680-5d76-11eb-9c26-7dd8cf850f2c.png)

Router A receives router B with a level <-90dBm
This implies that the signal is often too small for the routers to negotiate.

The Sonoff receives router A with -74dBm, router B with -80dBm. The FritzBox receive the Sonoff with -70dBm.

Question: Is the Sonoff (Tasmota) negotiating with Router B?
If not: sporadic problems, because UDP does not check whether a message has been sent, annoying.

Similar situations with this kind of levels exist for other devices and networks. This is certainly not only the case with me.

In my opinion, a new router will not help, because it also can not receive router B properly.

The FritzBox keeps a table of the networks it receives, helpful. It could negotiate with these networks.  But this table is almost empty.

I don't know at the moment whether a mesh or a repeater can solve the problem.

Wolfgang

**Comment by Jason2866** [comment]
Router B is a network where the wifi credentials are not known. Right?
So this router is out of any interest for the Tasmota device. It is "just" generating wifi hf noise.
Imho Mesh and Repeater both is a suboptimal choice. Connect a wired AP driven via PoE.
All your problems will be gone.

**Comment by wchulze** [comment]
Thanks for the hint

Exactly this seems to be the problem:

 **Router B "only" generates strong WLAN HF noise.**

That disturbs the UDP transmission. Due to level: **no** “Distributed Coordination Function” can takes place with router A ( see above ).

A wired AP means what the name implies: additionall "wire". ok.

Do this AP spans an additional network?  In this case: will the PCs in house all know each other? Is the WiFi printer still available, does Alexa know all participants ...?

Wolfgang

**Comment by Jason2866** [comment]
It is like that the router has just has a bigger wifi coverage. Okay not completely the AP should use a different channel (ssid is the same). It makes NO difference to which AP devices are connected.
So no, not a additional network. One bigger network.

**Comment by wchulze** [comment]
An AP requires an additional cable, which is difficult to install later.
Some time ago I made tests with a Fritz Repeater, the results were good eegarding the coverage, but many participants no longer knew each other. Maybe the repeater was not suitable, although the router and repeater were from AVM.
That's why I'm currently quite hesitant.

Maybe another repeater works so that all participants know each other. Whether a mesh will help is questionable for me. Do you have any knowledge about the behavior of a repeater or mesh?

Wolfgang

**Comment by ascillato** [comment]
Repeaters are known to not broadcast UDP. So, your issue will be worst.

**Comment by wchulze** [comment]
@ascillato 
Thank's, an important piece of info

**Comment by eavel22** [comment]
I have the same problem (i think) that wchulze is talking about. I also use a AVM Fritzbox (6590) and two AVM WLAN Repeater 1750E. I try to use a tasmota 9.1.0[OTA] - flashed LED dimmer/switch [type LC-SS-369 Tuya-software] with Alexa (on/off/dimming). First I thought everything works as expected but after some minutes of "idle" Alexa cannot talk to the dimmer anymore and she tells me that there seems to be a network problem because the device does not answer. And if I repeat my order to switch on/off the device - it works, immediately. This behaviour is stable and continuous. It seems that the device is in a kind of sleep mode and it takes the first call to wake up. After that everything works fine until I leave it for a few minutes. (I tried "sleep 0" in the tasmota console but it doesnt effect anything). 
And in doesnt matter if I put the device in the range of a repeater or next to the router. I've made all the settings in the router as you suggested (multicast, fixed WLAN channel [for me it is ch 1], fixed IP assignment in the router].

Do you have any more ideas how to deal with that? What else can be helpful to try out? It would be great to get this thing to work like it should do. Thank you all for your help.

**Comment by ascillato** [comment]
Try to ping the device and after that, try a command from Alexa. Do you have a correct response or do you see the same behavior?

**Comment by raphamotta** [comment]
I believe it's no ping related, because when I had this problem before enable IGMP snooping, the ping was OK for hours. Ping is TCP and alexa command is UDP, so maybe that's not the problem

**Comment by ascillato** [comment]
I know, but a ping makes your Router to update its ARP table. So if you ping the device where you see your issue, and right after that, you make Alexa to send a command and it responds, that means a problem in ARP. If the behavior is exactly the same, the issue is in another place. That is why the ping test was asked.

**Comment by raphamotta** [comment]
> I know, but a ping makes your Router to update its ARP table. So if you ping the device where you see your issue, and right after that, you make Alexa to send a command and it responds, that could means a problem in ARP. But, If the behavior is exactly the same, the issue is in another place. That is why the ping test was asked.

Ow, I understand! Thanks for the explanation!

**Comment by ascillato** [comment]
Ok, what is the result of the test? It works?

**Comment by eavel22** [comment]
Hey :-)
It works! If I ping the dimmer first Alexa can talk to it after that. It works inside the LAN and also via VPN.
So whats next? Do you have an idea hownto solve the problem?

Thank you 👍🏻

**Comment by ascillato** [comment]
You can try `setoption41 40`

**Comment by eavel22** [comment]
Wow, thank you. That seems work. I will test it for some days and report.
For now I am very happy.

**Comment by ascillato2** [comment]
Ok, So from Tasmota Software side, there isn't much we can do for wifi networks improvements.

Please, check the advises and the video at https://github.com/arendst/Tasmota/issues/1879#issuecomment-364843156 for really good tips while improving your wifi network.

**Comment by wchulze** [comment]
Thank you for all the effort.

Wolfgang
