### ISSUE TITLE
Compile error 15.1.0 for ESP32 when JPEG_PICTS is enabled

### ISSUE THREAD

**Issue by helmar74** [arendst/Tasmota#24001]
### PROBLEM DESCRIPTION
I have a problem with own compiled Tasmota 15.1.0.
I changed user_config_override and platformio_override like the attached files.
The compilation worked until 15.0.1 buit failed with 15.1.0 in VSC with error:

```
Retrieved `.pio/build/tasmota32/lib71d/ESP8266Audio/libopus/celt/celt_decoder.c.o' from cache
Retrieved `.pio/build/tasmota32/lib71d/ESP8266Audio/libopus/celt/celt_encoder.c.o' from cache
*** [.pio/build/tasmota32/src/tasmota.ino.cpp.o] Error 1
==================================================================================================================================================================================================== [FAILED] Took 68.90 seconds ====================================================================================================================================================================================================

Environment    Status    Duration
-------------  --------  ------------
tasmota32      FAILED    00:01:08.904
======================================================
```

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Problem is not scripter related, in this case open a discussion and tag  gemu2015
- [X] Device used (e.g., Sonoff Basic): ESP32 with RA8876 Display
- [X ] Tasmota binary firmware version number used: 15.1.0
-  [ ] Pre-compiled
  - [X] Self-compiled
- [X] Flashing tools used: VSC
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by helmar74** [comment]
[user_config_override_RA8876_ST7789_SDCARD_JPEG_ESP32_Display_25_Mhz__JPEG_v1400.txt](https://github.com/user-attachments/files/22864780/user_config_override_RA8876_ST7789_SDCARD_JPEG_ESP32_Display_25_Mhz__JPEG_v1400.txt)
[platformio_override_RA8876_ST7789_SDCARD_JPEG_ESP32_v1400.txt](https://github.com/user-attachments/files/22864779/platformio_override_RA8876_ST7789_SDCARD_JPEG_ESP32_v1400.txt)

Here my config files....

Anyone an idea, what's going wrong here?

**Comment by helmar74** [comment]
Tried compiling again, detailed error log:

```
DF Modes: Finder ~ chain, Compatibility ~ strict
Found 133 compatible libraries
Scanning dependencies...
Dependency Graph
|-- Adafruit CCS811 Library @ 1.0.0
|-- Adafruit MAX31865 library @ 1.0.1
|-- Adafruit MCP9808 Library @ 1.1.2
|-- Adafruit PM25 AQI Sensor @ 1.0.6
|-- Adafruit SGP30 Sensor @ 1.2.0
|-- Adafruit SGP40 Sensor @ 1.1.0
|-- Adafruit VEML7700 Library @ 1.0.0
|-- Adafruit seesaw Library @ 1.3.1
|-- ESP8266Audio @ 1.9.5
|-- BME8563
|-- EEPROM 24C128_256_521
|-- FFat @ 3.3.0
|-- FS @ 3.3.0
|-- FastCRC @ 1.44
|-- HttpClient light @ 1.0
|-- I2Cdevlib-Core
|-- IniFile @ 1.3.0+tasmota
|-- JPEGDEC @ 1.8.3
|-- TasmotaLList @ 1.0
|-- LibTeleinfo @ 1.1.7
|-- MPU6050 I2C
|-- Mutichannel_Gas_Sensor @ 0.0.1
|-- NTP Library
|-- esp-nimble-cpp @ 2.2.1
|-- OpenTherm Library @ 1.1.5
|-- Process_control @ 1.0.0
|-- SPL06-007 @ 0.1.0
|-- ESP Mail Client @ 3.4.9
|-- ScioSense ENS16x @ 8.0.0
|-- ScioSense ENS210 @ 3.0.0
|-- Sensirion I2C SGP41 @ 0.1.0
|-- SevenSegmentTM1637 @ 1.1.0
|-- TasmotaLED @ 0.1
|-- UdpListener @ 1.0
|-- Unishox (De)Compressor @ 1.0
|-- VL53L0X @ 1.0.2
|-- VL53L1X @ 1.0.1
|-- TLS mini client derived from Arduino @ 1.0
|-- Zip-readonly-FS @ 1.0
|-- Berry @ 7.0
|-- Berry Tasmota mapping @ 1.0
|-- Berry int64 implementation for 32 bits architecture @ 1.1
|-- HASPmota @ 1.0
|-- Berry mapping to C @ 1.0
|-- Berry animation library for WS2812 leds @ 0.1
|-- Berry Animation Framework @ 1.0.0
|-- Berry custom template @ 0.1
|-- Berry Matter protocol implementation @ 0.1
|-- headers
|-- ccronexpr
|-- lvgl @ 9.3.0
|-- esp_wireguard_tasmota @ 0.4.2
|-- WebServer @ 3.3.0
|-- ESP32-to-ESP8266-compat @ 0.0.2
|-- ams @ 1.0
|-- Berry mapping to LVGL @ 1.0
|-- arduino-mcp2515-1.0.1
|-- re1.5 @ 0.9
|-- LVGL_assets @ 7.0
|-- A4988_Stepper @ 0.0.1
|-- Adafruit Fingerprint Sensor Library @ 2.1.0
|-- Adafruit GFX Library @ 1.5.6
|-- Adafruit LED Backpack Library @ 1.1.6
|-- Adafruit TSL2591
|-- Micro-RTSP @ 0.1.6
|-- DHT sensor library @ 1.4.3
|-- DNSServer @ 3.3.0
|-- DS2480 Library @ 0.1.0
|-- ESP8266SAM @ 1.0.1
|-- ESPFtpServer @ 0.1.0
|-- ESPmDNS @ 3.3.0
|-- Ethernet @ 3.3.0
|-- FT5206_Library @ 1.0.0
|-- FrogmoreScd30
|-- FrogmoreScd40
|-- GT911
|-- IRremoteESP8266 @ 2.8.6
|-- JSMN JSON parser customized and optimized for ESP8266 and Tasmota @ 1.0
|-- KeeloqLib @ 1.1
|-- LOLIN_HP303B @ 1.0.0
|-- LedControl @ 1.0.6
|-- LinkedList
|-- LiquidCrystal_I2C
|-- LittleFS @ 3.3.0
|-- LoRa @ 0.8.0
|-- MFRC522 @ 1.4.7
|-- MLX90640
|-- MPU_accel
|-- BlueRobotics_MS5837
|-- NewPing @ 1.9.1
|-- OneWire @ 2.3.2
|-- PubSubClient @ 2.8
|-- QuickEspNow @ 0.8.1
|-- RA8876 @ 1.0.2
|-- rc-switch @ 1.0.0
|-- RF24 @ 1.3.3
|-- RadioLib @ 6.4.2
|-- Ext-printf @ 1.0
|-- SD @ 3.3.0
|-- SD_MMC @ 3.3.0
|-- SPI @ 3.3.0
|-- Sensirion I2C SEN5X @ 0.2.0
|-- TM1638plus @ 1.7.0
|-- TasmotaModbus @ 3.6.0
|-- TasmotaSerial @ 3.7.0
|-- Ticker @ 3.3.0
|-- Joba_Tsl2561 @ 2.0.10
|-- WiFiHelper @ 1.0.0
|-- WiFi @ 3.3.0
|-- Wire @ 3.3.0
|-- XPT2046_Touchscreen
|-- base64 @ 1.1.1
|-- BME68x
|-- Waveshare esp 2.9 inch e-paper display driver @ 1.0
|-- Waveshare esp 4.2 inch e-paper display driver @ 1.0
|-- Display renderer @ 1.0
|-- ESP KNX IP Library @ 0.5.2
|-- HPMA115S0 Arduino Library @ 1.0.0
|-- mp3_shine_esp32 @ 1.0.0
|-- BearSSL @ 0.6
|-- universal display Library @ 0.1
Building in release mode
Compiling .pio/build/tasmota32/src/tasmota.ino.cpp.o
In file included from tasmota/my_user_config.h:1372,
                 from /home/helmar/Dokumente/Tasmota-master_v1510_RA8876/tasmota/tasmota.ino:27:
tasmota/user_config_override.h:24:2: warning: #warning **** user_config_override.h: Using Settings from this File **** [-Wcpp]
   24 | #warning **** user_config_override.h: Using Settings from this File ****
      |  ^~~~~~~
/home/helmar/Dokumente/Tasmota-master_v1510_RA8876/tasmota/tasmota_support/support_jpeg.ino:123:38: error: 'jpg_scale_t' has not been declared
  123 | esp_err_t esp_jpg_decode(size_t len, jpg_scale_t scale, jpg_reader_cb reader, jpg_writer_cb writer, void * arg);
      |                                      ^~~~~~~~~~~
/home/helmar/Dokumente/Tasmota-master_v1510_RA8876/tasmota/tasmota_support/support_jpeg.ino:123:57: error: 'jpg_reader_cb' has not been declared
  123 | esp_err_t esp_jpg_decode(size_t len, jpg_scale_t scale, jpg_reader_cb reader, jpg_writer_cb writer, void * arg);
      |                                                         ^~~~~~~~~~~~~
/home/helmar/Dokumente/Tasmota-master_v1510_RA8876/tasmota/tasmota_support/support_jpeg.ino:123:79: error: 'jpg_writer_cb' has not been declared
  123 | esp_err_t esp_jpg_decode(size_t len, jpg_scale_t scale, jpg_reader_cb reader, jpg_writer_cb writer, void * arg);
      |                                                                               ^~~~~~~~~~~~~
/home/helmar/Dokumente/Tasmota-master_v1510_RA8876/tasmota/tasmota_support/support_jpeg.ino:126:68: error: 'jpg_scale_t' has not been declared
  126 | bool jpg2rgb888(const uint8_t *src, size_t src_len, uint8_t * out, jpg_scale_t scale)
      |                                                                    ^~~~~~~~~~~
/home/helmar/Dokumente/Tasmota-master_v1510_RA8876/tasmota/tasmota_support/support_jpeg.ino: In function 'bool jpg2rgb888(const uint8_t*, size_t, uint8_t*, int)':
/home/helmar/Dokumente/Tasmota-master_v1510_RA8876/tasmota/tasmota_support/support_jpeg.ino:135:39: error: invalid conversion from 'size_t (*)(void*, size_t, uint8_t*, size_t)' {aka 'unsigned int (*)(void*, unsigned int, unsigned char*, unsigned int)'} to 'int' [-fpermissive]
  135 |     if(esp_jpg_decode(src_len, scale, _jpg_read, _rgb_write, (void*)&jpeg) != ESP_OK){
      |                                       ^~~~~~~~~
      |                                       |
      |                                       size_t (*)(void*, size_t, uint8_t*, size_t) {aka unsigned int (*)(void*, unsigned int, unsigned char*, unsigned int)}
/home/helmar/Dokumente/Tasmota-master_v1510_RA8876/tasmota/tasmota_support/support_jpeg.ino:123:71: note:   initializing argument 3 of 'esp_err_t esp_jpg_decode(size_t, int, int, int, void*)'
  123 | esp_err_t esp_jpg_decode(size_t len, jpg_scale_t scale, jpg_reader_cb reader, jpg_writer_cb writer, void * arg);
      |                                                         ~~~~~~~~~~~~~~^~~~~~
/home/helmar/Dokumente/Tasmota-master_v1510_RA8876/tasmota/tasmota_support/support_jpeg.ino:135:50: error: invalid conversion from 'bool (*)(void*, uint16_t, uint16_t, uint16_t, uint16_t, uint8_t*)' {aka 'bool (*)(void*, short unsigned int, short unsigned int, short unsigned int, short unsigned int, unsigned char*)'} to 'int' [-fpermissive]
  135 |     if(esp_jpg_decode(src_len, scale, _jpg_read, _rgb_write, (void*)&jpeg) != ESP_OK){
      |                                                  ^~~~~~~~~~
      |                                                  |
      |                                                  bool (*)(void*, uint16_t, uint16_t, uint16_t, uint16_t, uint8_t*) {aka bool (*)(void*, short unsigned int, short unsigned int, short unsigned int, short unsigned int, unsigned char*)}
/home/helmar/Dokumente/Tasmota-master_v1510_RA8876/tasmota/tasmota_support/support_jpeg.ino:123:93: note:   initializing argument 4 of 'esp_err_t esp_jpg_decode(size_t, int, int, int, void*)'
  123 | esp_err_t esp_jpg_decode(size_t len, jpg_scale_t scale, jpg_reader_cb reader, jpg_writer_cb writer, void * arg);
      |                                                                               ~~~~~~~~~~~~~~^~~~~~
/home/helmar/Dokumente/Tasmota-master_v1510_RA8876/tasmota/tasmota_xdrv_driver/xdrv_13_display.ino: At global scope:
/home/helmar/Dokumente/Tasmota-master_v1510_RA8876/tasmota/tasmota_xdrv_driver/xdrv_13_display.ino:2407:68: error: 'jpg_scale_t' has not been declared
 2407 | bool jpg2rgb888(const uint8_t *src, size_t src_len, uint8_t * out, jpg_scale_t scale);
      |                                                                    ^~~~~~~~~~~
/home/helmar/Dokumente/Tasmota-master_v1510_RA8876/tasmota/tasmota_xdrv_driver/xdrv_13_display.ino:2408:68: error: 'jpg_scale_t' has not been declared
 2408 | bool jpg2rgb565(const uint8_t *src, size_t src_len, uint8_t * out, jpg_scale_t scale);
      |                                                                    ^~~~~~~~~~~
/home/helmar/Dokumente/Tasmota-master_v1510_RA8876/tasmota/tasmota_xdrv_driver/xdrv_13_display.ino: In function 'void Draw_RGB_Bitmap(char*, uint16_t, uint16_t, uint8_t, bool, uint16_t, uint16_t)':
/home/helmar/Dokumente/Tasmota-master_v1510_RA8876/tasmota/tasmota_xdrv_driver/xdrv_13_display.ino:2515:53: error: 'jpg_scale_t' was not declared in this scope
 2515 |                 if (jpg2rgb888(mem, size, out_buf, (jpg_scale_t)JPG_SCALE_NONE)) {
      |                                                     ^~~~~~~~~~~
/home/helmar/Dokumente/Tasmota-master_v1510_RA8876/tasmota/tasmota_xdrv_driver/xdrv_13_display.ino: In function 'void Draw_jpeg(uint8_t*, uint16_t, uint16_t, uint16_t, uint8_t)':
/home/helmar/Dokumente/Tasmota-master_v1510_RA8876/tasmota/tasmota_xdrv_driver/xdrv_13_display.ino:2566:41: error: 'jpg_scale_t' was not declared in this scope
 2566 |       jpg2rgb565(mem, jpgsize, rgbmem, (jpg_scale_t)scale);
      |                                         ^~~~~~~~~~~
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/control_SNR.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/control_audio_bandwidth.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/control_codec.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/debug.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/dec_API.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/decode_core.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/decode_frame.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/decode_indices.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/decode_parameters.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/decode_pitch.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/decode_pulses.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/decoder_set_fs.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/enc_API.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/encode_indices.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/encode_pulses.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/LTP_analysis_filter_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/LTP_scale_ctrl_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/apply_sine_window_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/autocorr_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/burg_modified_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/corrMatrix_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/encode_frame_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/find_LPC_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/find_LTP_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/find_pitch_lags_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/find_pred_coefs_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/k2a_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/k2a_Q16_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/noise_shape_analysis_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/pitch_analysis_core_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/process_gains_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/regularize_correlations_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/residual_energy16_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/residual_energy_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/schur64_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/schur_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/vector_ops_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/fixed/warped_autocorrelation_FIX.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/gain_quant.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/init_decoder.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/init_encoder.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/inner_prod_aligned.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/interpolate.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/lin2log.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/log2lin.c.o' from cache
Retrieved `.pio/build/tasmota32/libe0a/ESP8266Audio/libopus/silk/pitch_est_tables.c.o' from cache
*** [.pio/build/tasmota32/src/tasmota.ino.cpp.o] Error 1
==================================================================================================================================================================================================== [FAILED] Took 61.04 seconds ====================================================================================================================================================================================================

Environment    Status    Duration
-------------  --------  ------------
```

**Comment by helmar74** [comment]
If I add this in user_config_override, I can compile, but JPGs aren't working afterwards:
```
#undef JPEG_PICTS 
```

Looks like it is a similar issue as mentionend here:
https://github.com/arendst/Tasmota/discussions/21372 

> for core3 you have to change this line in support_jpeg.ino (change uint32_t to size_t)
static size_t _jpg_read(void * arg, size_t index, uint8_t *buf, size_t len)
it then it will compile.
however jpeg decoder is broken with core3 and will crash.
the jpeg decoder used to be in flash and now is in ROM which seems not be well tested.
the ra8876 driver can still be used but must be used together with USE_UNIVERSAL_TOUCH.
the universal touch driver is now integrated into the RA8876 driver

**Comment by helmar74** [comment]
@gemu2015 : 
Does it make sense to revert the change , mentionend in https://github.com/arendst/Tasmota/discussions/21372

> for core3 you have to change this line in support_jpeg.ino (change uint32_t to size_t)
static size_t _jpg_read(void * arg, size_t index, uint8_t *buf, size_t len)
it then it will compile.

**Comment by gemu2015** [comment]
very few people seem to use jpegs with displaytext. it is broken since a while.
i have fixed it as i use jpegs in several devices but did not yet pr my changes.
you may use my fork to get it going or just copy these file to tasmota dev from my fork.
xdrv_13_display.ino
support_jpeg.ino
and folder JPEGDEC

**Comment by helmar74** [comment]
> use jpegs in several devices but did not yet pr my changes.
> you may use my fork to get it going or just copy these file to tasmota dev from my fork.

I replaced the 2 ino files and the JPEGDEC folder in current Tasmota v 15.1.0 which ends in compile error:

```
Building .pio/build/tasmota32/bootloader.bin
Generating partitions .pio/build/tasmota32/partitions.bin
esptool v5.1.0
Creating ESP32 image...
Merged 2 ELF sections.
Successfully created ESP32 image.
Compiling .pio/build/tasmota32/lib241/Wire/Wire.cpp.o
Compiling .pio/build/tasmota32/libfee/Adafruit_CCS811-1.0.0.14/Adafruit_CCS811.cpp.o
In file included from tasmota/my_user_config.h:1372,
                 from /home/helmar/Dokumente/Tasmota-master_v1510_RAoo76_GEMU/tasmota/tasmota.ino:27:
tasmota/user_config_override.h:24:2: warning: #warning **** user_config_override.h: Using Settings from this File **** [-Wcpp]
   24 | #warning **** user_config_override.h: Using Settings from this File ****
      |  ^~~~~~~
Compiling .pio/build/tasmota32/lib8fa/SPI/SPI.cpp.o
/home/helmar/Dokumente/Tasmota-master_v1510_RAoo76_GEMU/tasmota/tasmota_support/support_jpeg.ino:26:10: fatal error: esp_jpg_decode.h: No such file or directory

************************************************************************
* Looking for esp_jpg_decode.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_jpg_decode.h"
* Web  > https://registry.platformio.org/search?q=header:esp_jpg_decode.h
*
************************************************************************

   26 | #include "esp_jpg_decode.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio/build/tasmota32/src/tasmota.ino.cpp.o] Error 1
==================================================================================================================================================================================================== [FAILED] Took 31.70 seconds ====================================================================================================================================================================================================

Environment    Status    Duration
-------------  --------  ------------
tasmota32      FAILED    00:00:31.699
=============================================================================================================================================================================================== 1 failed, 0 succeeded in 00:00:31.699 ===============================================================================================================================================================================================

 *  Der Terminalprozess "platformio 'run'" wurde mit folgendem Exitcode beendet: 1. 
 *  Das Terminal wird von Aufgaben wiederverwendet, drücken Sie zum Schließen eine beliebige Taste. 

```

**Comment by helmar74** [comment]
I also copied /lib/libesp32_dev/ESP32_JPDEC ... but it still don't work....
```
Indexing .pio/build/tasmota32/libfee/libAdafruit_CCS811-1.0.0.14.a
Compiling .pio/build/tasmota32/liba3d/Adafruit_MAX31865-Tasmota-1.1.0/Adafruit_MAX31865.cpp.o
Compiling .pio/build/tasmota32/lib49a/Adafruit_MCP9808_Tasmota/Adafruit_MCP9808.cpp.o
/home/helmar/Dokumente/Tasmota-master_v1510_RAoo76_GEMU/tasmota/tasmota_support/support_jpeg.ino:26:10: fatal error: esp_jpg_decode.h: No such file or directory

************************************************************************
* Looking for esp_jpg_decode.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_jpg_decode.h"
* Web  > https://registry.platformio.org/search?q=header:esp_jpg_decode.h
*
************************************************************************

   26 | #include "esp_jpg_decode.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio/build/tasmota32/src/tasmota.ino.cpp.o] Error 1
Compiling .pio/build/tasmota32/lib03e/Adafruit_BusIO/Adafruit_BusIO_Register.cpp.o
==================================================================================================================================================================================================== [FAILED] Took 29.25 seconds ====================================================================================================================================================================================================

Environment    Status    Duration
-------------  --------  ------------
tasmota32      FAILED    00:00:29.252
=============================================================================================================================================================================================== 1 failed, 0 succeeded in 00:00:29.252 ===============================================================================================================================================================================================

 *  Der Terminalprozess "platformio 'run'" wurde mit folgendem Exitcode beendet: 1. 
 *  Das Terminal wird von Aufgaben wiederverwendet, drücken Sie zum Schließen eine beliebige Taste. 

```

**Comment by gemu2015** [comment]
You must add the lib to 
lib_extra_dirs In platform override

**Comment by gemu2015** [comment]
add after
lib_extra_dirs          = ${library.lib_extra_dirs}

lib/libesp32_div/ESP32_JPDEC

**Comment by helmar74** [comment]
Thanks that worked.
Just for summary:
I copied 
tasmota/tasmota_xdrv_driver/xdrv_13_display.ino
tasmota/tasmota_support/support_jpeg.ino
folder libesp32_div/JPEGDEC
from fork https://github.com/gemu2015/Sonoff-Tasmota

I changed/added in platform_override.ini in section
; uncommented
lib/libesp32_div
; added
lib/libesp32_div/ESP32_JPDEC

After that I was able to compile successfully Tasmota Master 15.1.0

@gemu2015 : Once you merged your PR's to development version of Tasmota, you can just ping me, and I'll try to compile "official" tasmota development.

Thanks a lot for your help!
